### ISSUE TITLE
MC 1.16.4 Update

### ISSUE THREAD

**Issue by nanohard** [BackendLlama/FloatingPets#1]
I would love to see this working in 1.16.4.
Tried it, didn't load. It should, because it was just a patch release, but I guess the dev over there doesn't believe in semantic versioning, which is confusing.

**Comment by BackendLlama** [comment]
The latest update strangely had a bump in NMS version (which resulted in new names for obfuscated fields and methods) and thus required me to create a new module. I haven't had much time to spend on this project which resulted in this delay unfortunately. I've posted a new update on Spigot, should be working as intended!
